#!/usr/bin/env bash
# Helper to generate an Alembic autogenerate revision locally.
# Usage: cd backend && ../scripts/generate_migration.sh "migration message"
set -e
msg=${1:-"autogenerated migration"}

python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
alembic revision --autogenerate -m "$msg"

echo "Migration generated. Review and commit changes under backend/alembic/versions/"
